#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONDA_ENV="${CONDA_ENV:-unitale-tts-local}"

export HF_MIRROR_DIR="${HF_MIRROR_DIR:-$HOME/hf-mirror}"
export QWEN_MODEL_DIR="${QWEN_MODEL_DIR:-$HF_MIRROR_DIR/Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign}"
export INDEXTTS_MODEL_DIR="${INDEXTTS_MODEL_DIR:-$HF_MIRROR_DIR/IndexTeam/IndexTTS-2}"
export INDEXTTS_CFG_PATH="${INDEXTTS_CFG_PATH:-$INDEXTTS_MODEL_DIR/config.yaml}"
export INDEXTTS_CODE_DIR="${INDEXTTS_CODE_DIR:-$PROJECT_DIR/vendor/index-tts}"
export QWEN_LIBS="${QWEN_LIBS:-$PROJECT_DIR/vendor/qwen_libs}"
export PROMPTS_DIR="${PROMPTS_DIR:-$PROJECT_DIR/prompts}"
export RUNTIME_CACHE_DIR="${RUNTIME_CACHE_DIR:-$PROJECT_DIR/.cache/runtime}"
export LOCAL_FILES_ONLY="${LOCAL_FILES_ONLY:-1}"
export PRELOAD_INDEXTTS="${PRELOAD_INDEXTTS:-0}"
export CLEAN_UNKNOWN_PYTHON_PROCESSES="${CLEAN_UNKNOWN_PYTHON_PROCESSES:-0}"
export INDEXTTS_DEVICE="${INDEXTTS_DEVICE:-}"
export INDEXTTS_USE_FP16="${INDEXTTS_USE_FP16:-1}"
export INDEXTTS_USE_CUDA_KERNEL="${INDEXTTS_USE_CUDA_KERNEL:-0}"
export INDEXTTS_NUM_BEAMS="${INDEXTTS_NUM_BEAMS:-1}"
export CUDA_RELEASE_DELAY="${CUDA_RELEASE_DELAY:-2.0}"
export HOST="${HOST:-0.0.0.0}"
export PORT="${PORT:-8300}"

export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True,max_split_size_mb:128}"
export CUDA_MODULE_LOADING="${CUDA_MODULE_LOADING:-LAZY}"
export NUMBA_CACHE_DIR="${NUMBA_CACHE_DIR:-$RUNTIME_CACHE_DIR/numba}"
export MPLCONFIGDIR="${MPLCONFIGDIR:-$RUNTIME_CACHE_DIR/matplotlib}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$RUNTIME_CACHE_DIR/xdg}"
mkdir -p "$PROMPTS_DIR" "$NUMBA_CACHE_DIR" "$MPLCONFIGDIR" "$XDG_CACHE_HOME"

echo "=================================================="
echo "   Unitale AI local backend"
echo "=================================================="
echo "Conda env:           $CONDA_ENV"
echo "Qwen model:          $QWEN_MODEL_DIR"
echo "IndexTTS2 model:     $INDEXTTS_MODEL_DIR"
echo "IndexTTS2 code:      $INDEXTTS_CODE_DIR"
echo "Qwen sidecar libs:   $QWEN_LIBS"
echo "Prompts dir:         $PROMPTS_DIR"
echo "IndexTTS2 device:    ${INDEXTTS_DEVICE:-auto}"
echo "IndexTTS2 fp16:      $INDEXTTS_USE_FP16"
echo "IndexTTS2 beams:     $INDEXTTS_NUM_BEAMS"
echo "CUDA kernel:         $INDEXTTS_USE_CUDA_KERNEL"
echo "Listen:              http://$HOST:$PORT"
echo "Health:              http://127.0.0.1:$PORT/v1/health"
echo "=================================================="

cd "$PROJECT_DIR"
exec conda run --no-capture-output -n "$CONDA_ENV" python api.py
